communities/urls.py
from django.urls import path
from . import views

#TODO split into seprate apps
urlpatterns = [

    path('', views.home, name="home"),
    path('auth', views.userLogin, name="login"),
    path('auth/register', views.userRegister, name="register"),
    path('auth/logout', views.userLogout, name="logout"),
    path('profile/<str:id>/', views.Profile, name="profile"),
    path('update-profile', views.userUpdate, name="update-user"),

    path('topics', views.tags, name="topics"),
    path('recent',  views.recent,  name="recent"),


    path('goal/<str:id>/', views.getGoal,  name="goal"),
    path('create-goal', views.createGoal, name="create-goal"),
    path('update-goal/<str:id>/', views.updateGoal, name="update-goal"),
    path('delete-goal/<str:id>/', views.deleteGoal, name="delete-goal"),

    path('delete-conversation/<str:id>/', views.deleteCon, name="delete-conversation"),
]

notreddit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('communities.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

communities/models.py
from django.db import models
from sqlalchemy import true
from django.contrib.auth.models import User

# Create your models here.


class userProfile(models.Model):
    user = models.OneToOneField(
        to=User, on_delete=models.CASCADE, primary_key=True)
    bio = models.TextField(null=true)
    created = models.DateTimeField(auto_now_add=true)
    avatar = models.ImageField(upload_to='avatars', default='avatar.svg')

    def __str__(self):
        return str(self.user.username)


class Tag(models.Model):

    name = models.CharField(max_length=50)
    # isfollowing

    def __str__(self):
        return self.name


class Goal(models.Model):
    created_by = models.ForeignKey(
        to=User, on_delete=models.SET_NULL, null=True)
    members = models.ManyToManyField(
        to=User, related_name='members', blank=true)
    tag = models.ForeignKey(to=Tag, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=30)
    description = models.TextField(max_length=200)
    updated = models.DateTimeField(auto_now=true)
    created = models.DateTimeField(auto_now_add=true)

    def __str__(self):
        return self.name
    # conversation

    class Meta:
        ordering = ["-updated", "-created"]


class Conversation(models.Model):
    user = models.ForeignKey(
        to=User, on_delete=models.SET_NULL, null=True)
    goal = models.ForeignKey(to=Goal, on_delete=models.CASCADE)
    body = models.TextField(max_length=200)
    updated = models.DateTimeField(auto_now=true)
    created = models.DateTimeField(auto_now_add=true)

    class Meta:
        ordering = ["-updated", "-created"]

    def __str__(self):
        return self.body[0:20]

communities/forms.py
import profile
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import userProfile, Goal
from django.contrib.auth.models import User


class newUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'username', 'password1', 'password2']


class userProfileForm(ModelForm):
    class Meta:
        model = userProfile
        fields = '__all__'
        exclude = ['user']


class goalForm():
    class Meta:
        model = Goal
        fields = '__all__'
        exclude = ['created_by', 'members']

communities/views.py
from multiprocessing import context
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.contrib import messages
from django.db.models import Q
from .models import Tag, Conversation, Goal, userProfile
from django.contrib.auth import authenticate, login, logout
from .forms import newUserCreationForm, userProfileForm, goalForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
# TODO move users to seperate app


def userLogin(request):
    toDisplay = 'login'
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'POST':
        try:
            # TODO find work around for email Abstract user did not work
            username = request.POST.get('username').lower()
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
        except:
            messages.error(request, '😕 .something went wrong')
    context = {'toDisplay': toDisplay}
    return render(request, 'communities/auth.html', context)


def userRegister(request):
    form = newUserCreationForm()
    if request.method == 'POST':
        try:
            isValid = newUserCreationForm(request.POST).is_valid()
            if isValid == True:
                user = newUserCreationForm(request.POST).save(commit=False)
                user.username = user.username.lower()
                user.save()
                userProfile.objects.create(user=user)
                login(request, user)
                return redirect('home')
        except:
            messages.error(
                request, '😕 .something went wrong with registration .')
    context = {'form': form}
    return render(request, 'communities/auth.html', context)


def userLogout(request):
    logout(request)
    return redirect('home')


def Profile(request, id):
    try:
        user = User.objects.get(username=id)
        profile = user.userprofile
        goals = user.goal_set.all()
        conversations = user.conversation_set.all()
        tags = Tag.objects.all()
        context = {'user': user, 'profile': profile, 'goals': goals,
                   'conversations': conversations, 'tags': tags}
        return render(request, 'communities/user_profile.html', context)
    except:
        messages.error(request, '😕 .User does not exist .')
        # TODO home ||  profile with message
        return HttpResponse("failure")

# TODO add LOGIN_URL in settings.py later


@login_required(login_url='/auth')
def userUpdate(request):
    user = request.user
    userForm = newUserCreationForm(instance=user)
    profileForm = userProfileForm(instance=user.userprofile)
    context = {'userform': userForm, 'profileform': profileForm}
    if request.method == 'POST':
        userForm = newUserCreationForm(request.POST, instance=user)
        profileForm = userProfileForm(
            request.POST, request.FILES, instance=user.userprofile)
        if userForm.is_valid():
            userForm.save()
            context['userform'] = userForm
        if profileForm.is_valid():
            profileForm.save()
            context['profileform'] = profileForm
        return redirect(to='profile', id=user.username)
    return render(request, 'communities/update_user.html', context)


def home(request):
    query = request.GET.get('query') if request.GET.get(
        'query') != None else ''
    # TODO limitt return in each query
    tags = Tag.objects.all()[0:9]

    goals = Goal.objects.filter(
        Q(tag__name__icontains=query) | Q(
            name__icontains=query) | Q(description__icontains=query)
    )
    goals_count = goals.count()

    goal_conversations = Conversation.objects.filter(
        Q(goal__tag__name__icontains=query))

    context = {'tags': tags, 'goals': goals, 'goals_count': goals_count,
               'goal_conversations': goal_conversations}
    return render(request, 'communities/home.html', context)


# TODO move goal to seperate app / rename tro communities
def getGoal(request, id):
    msg = "getting goal with id " + id
    goal = Goal.objects.get(id=id)
    conversations = goal.conversation_set.all()
    members = goal.members.all()
    context = {'goal': goal,
               'conversations': conversations, 'members': members}
    return render(request, 'communities/goal.html', context)


@login_required(login_url='/auth')
def createGoal(request):
    form = goalForm()
    tags = Tag.objects.all()
    try:
        if request.method == "POST":
            usertag = request.POST.get('tag')
            tag, created = Tag.objects.get_or_create(name=usertag)
            Goal.objects.create(
                created_by=request.user,
                name=request.POST.get('name'),
                tag=tag,
                description=request.POST.get('description')
            )
            return redirect('home')
    except:
        messages.error(request, "goal not created")
    context = {'form': form, 'tags': tags}
    return render(request, 'communities/goal_form.html', context)


@login_required(login_url='/auth')
def updateGoal(request, id):
    tags = Tag.objects.all()
    context = {"tags": tags}
    try:
        goal = Goal.objects.get(id=id)
        if goal.created_by == request.user:
            if request.method == 'POST':
                usertag = request.POST.get('tag')
                tag, created = Tag.objects.get_or_create(name=usertag)
                goal.objects.update(tag=tag, name=request.POST.get(
                    'name'), description=request.POST.get("description"))
                return redirect('home')
            context['data'] = {'name': goal.name,
                               'description': goal.description, 'current_tag': goal.tag}
            return render(request, 'communities/goal_form.html', context)
        else:
            raise Exception('no permisson')
    except:
        messages.error(request, "You cannot make changes to this")
        return redirect('home')


@login_required(login_url='/auth')
def deleteGoal(request, id):
    try:
        goal = Goal.objects.get(id=id)
        if goal.created_by == request.user:
            if request.method == 'POST':
                goal.delete()
                return redirect('home')
            return render(request, 'communities/delete.html', {'obj': goal})
        else:
            raise Exception('no permisson')
    except:
        messages.error(request, "You cannot delete this")
        return redirect('home')


def tags(request):
    query = request.GET.get('query') if request.GET.get(
        'query') != None else ''
    tags = Tag.objects.filter(name__icontains=query)
    context = {'tags': tags}
    return render(request, 'communities/tags.html', context)


def recent(request):
    conversations = Conversation.objects.all()[0:20]
    return render(request, 'communities/recent.html', {'conversations':  conversations})


@login_required(login_url='/auth')
def deleteCon(request, id):
    try:
        print("works")
        goal = Conversation.objects.get(id=id)
        if goal.user == request.user:
            if request.method == 'POST':
                goal.delete()
                return redirect('home')
            return render(request, 'communities/delete.html', {'obj': goal})
        else:
            raise Exception('no permisson')
    except:
        messages.error(request, "You cannot delete this")
        return redirect('home')

communities/templates/communities/auth.html
{% extends 'base.html' %} {% block content %}
<main class="auth layout">
  {% if toDisplay == 'login' %}
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Login</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Grow with others</h2>

        <form class="form" action="" method="POST">
          {% csrf_token %}
          <div class="form__group form__group">
            <label for="room_name">Username</label>
            <input
              id="username"
              name="username"
              type="text"
              placeholder="e.g. john_doe"
            />
          </div>
          <div class="form__group">
            <label for="password">Password</label>
            <input
              id="password"
              name="password"
              type="password"
              placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
            />
          </div>

          <button class="btn btn--main" type="submit">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
              ></path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
              ></path>
            </svg>

            Login
          </button>
        </form>

        <div class="auth__action">
          <p>Haven't signed up yet?</p>
          <a href="{% url 'register' %}" class="btn btn--link">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
  {% else %}
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Register</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">We grow together</h2>

        <form class="form" action="" method="POST">
          {% csrf_token %} {% for field in form %}
          <div class="form__group form__group">
            <label for="room_name">{{field.label}}</label>
            {{field}}
          </div>
          {% endfor %}

          <button class="btn btn--main" type="submit">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
              ></path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
              ></path>
            </svg>

            Register
          </button>
        </form>

        <div class="auth__action">
          <p>Already signed up yet?</p>
          <a href="{% url 'login' %}" class="btn btn--link">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</main>
{% endblock content %}

communities/templates/communities/delete.html
{% extends 'base.html' %}

{% block content %}
<main class="delete-item layout">
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <a href="{{request.META.HTTP_REFERER}}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>Back</h3>
                </div>
            </div>
            <div class="layout__body">
                <form class="form" method="POST" action="">
                    {% csrf_token %}
                    <div class="form__group">
                        <p>Are you sure you want to delete "{{obj}}"?</p>
                    </div>

                    <div class="for__group">
                        <input class="btn btn--main" type="submit" value="Confirm" />
                    </div>

                </form>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

communities/templates/communities/feed_component.html
{% for goal in goals %}
<div class="roomListRoom">
    <div class="roomListRoom__header">
        <a href="{% url 'profile' goal.created_by.username %}" class="roomListRoom__author">
            <div class="avatar avatar--small">
                <img src="{{goal.created_by.userprofile.avatar.url}}" />
            </div>
            <span>@{{goal.created_by.username}}</span>
        </a>
        <div class="roomListRoom__actions">
            <span>{{goal.created|timesince}} ago</span>
        </div>
    </div>
    <div class="roomListRoom__content">
        <a href="{% url 'goal' goal.id %}">{{goal.name}}</a>
    </div>
    <div class="roomListRoom__meta">
        <a href="{% url 'goal' goal.id %}" class="roomListRoom__joined">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>user-group</title>
                <path
                    d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z">
                </path>
                <path
                    d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z">
                </path>
                <path
                    d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z">
                </path>
                <path
                    d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z">
                </path>
            </svg>
            {{goals.members.all.count}} Joined
        </a>
        <p class="roomListRoom__topic">{{goal.tag.name}}</p>
    </div>
</div>
{% endfor %}

communities/templates/communities/goal.html
{% extends 'base.html' %}

{% block content %}
<main class="profile-page layout layout--2">
  <div class="container">
    <!-- Room Start -->
    <div class="room">
      <div class="room__top">
        <div class="room__topLeft">
          <a href="{% url 'home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>  
          <h3>Study Room</h3>
        </div>
        {% if goal.created_by == request.user %}
        <div class="room__topRight">
          <a href="{% url 'update-goal' goal.id %}">
            <svg enable-background="new 0 0 24 24" height="32" viewBox="0 0 24 24" width="32"
              xmlns="http://www.w3.org/2000/svg">
              <title>edit</title>
              <g>
                <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
              </g>
              <g>
                <g>
                  <path
                    d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z" />
                </g>
                <g>
                  <path
                    d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z" />
                </g>
              </g>
            </svg>
          </a>
          <a href="{% url 'delete-goal' goal.id %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>remove</title>
              <path
                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
              </path>
            </svg>
          </a>
        </div>
        {% endif %}

      </div>
      <div class="room__box scroll">
        <div class="room__header scroll">
          <div class="room__info">
            <h3>{{goal.name}}</h3>
            <span>{{goal.created|timesince}} ago</span>
          </div>
          <div class="room__hosted">
            <p>Hosted By</p>
            <a href="{% url 'profile' goal.created_by.username %}" class="room__author">
              <div class="avatar avatar--small">
                <img src="{{goal.created_by.userprofile.avatar.url}}" />
              </div>
              <span>@{{goal.created_by.username}}</span>
            </a>
          </div>
          <!-- <div class="room__details">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi, tenetur laudantium? Dicta repellendus
            rerum consectetur, voluptatem repudiandae eum ea porro cupiditate provident nulla, deserunt, ab ipsum
            corporis laboriosam deleniti molestias?
          </div> -->
          <span class="room__topics">{{goal.name}}</span>
        </div>

        <div class="room__conversation">
          <div class="threads scroll">


            {% for conversation in conversations %}
            <div class="thread">
              <div class="thread__top">
                <div class="thread__author">
                  <a href="{% url 'profile' conversation.user.username %}" class="thread__authorInfo">
                    <div class="avatar avatar--small">
                      <img src="{{conversation.user.userprofile.avatar.url}}" />
                    </div>
                    <span>@{{conversation.user.username}}</span>
                  </a>
                  <span class="thread__date">{{conversation.created|timesince}} ago</span>
                </div>

                {% if request.user == conversation.user %}
                <a href="{% url 'delete-goal' conversation.id %}">
                  <div class="thread__delete">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                      <title>remove</title>
                      <path
                        d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                      </path>
                    </svg>
                  </div>
                </a>
                {% endif %}
              </div>
              <div class="thread__details">
                {{conversations.body}}
              </div>
            </div>
            {% endfor %}
          </div>
        </div>

      </div>
      <div class="room__message">
        <form action="" method="POST">
          {% csrf_token %}
          <input name="body" placeholder="Write your message here..." />
        </form>
      </div>
    </div>
    <!-- Room End -->

    <!--   Start -->
    <div class="participants">
      <h3 class="participants__top">Participants <span>({{participants.count}} Joined)</span></h3>
      <div class="participants__list scroll">
        {% for user in members %}
        <a href="{%  url 'profile' user.username %}" class="participant">
          <div class="avatar avatar--medium">
            <img src="{{user.userprofile.avatar.url}}" />
          </div>
          <p>
            {{user.first_name}}
            <span>@{{user.username}}</span>
          </p>
        </a>
        {% endfor %}
      </div>
    </div>
    <!--  End -->
  </div>
</main>
<script src="script.js"></script>
{% endblock content %}

communities/templates/communities/goal_form.html
{% extends 'base.html' %} {% block content %}
<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{{request.META.HTTP_REFERER}}">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
              ></path>
            </svg>
          </a>
          <h3>Create/Update Study Room</h3>
        </div>
      </div>
      <div class="layout__body">
        <form class="form" action="" method="POST">
          {% csrf_token %}

          <div class="form__group">
            <label for="room_topic">Enter a Topic</label>
            <input
              required
              type="text"
              {%if
              data.current_tag
              %}
              placeholder="{{data.current_tag}}"
              {%
              endif
              %}
              value="{{goal.tag.name}}"
              name="tag"
              list="topic-list"
            />
            <datalist id="topic-list">
              <select id="room_topic">
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
              </select>
            </datalist>
          </div>

          <div class="form__group">
            <label for="room_name">Room Name</label>
            <input
              {%if
              data.name
              %}
              placeholder="{{data.name}}"
              {%
              endif
              %}
              type="text"
              name="name"
              class="vTextField"
              maxlength="30"
              required=""
              id="id_name"
            />
          </div>

          <div class="form__group">
            <label for="room_description">Room Description</label>
            <textarea
              {%if
              data.name
              %}
              placeholder="{{data.description}}"
              {%
              endif
              %}
              name="description"
              cols="40"
              rows="10"
              class="vLargeTextField"
              maxlength="200"
              required=""
              id="id_description"
            ></textarea>
          </div>

          <!-- <div class="form__group">
            <label for="room_topic">Topic</label>
            <input required type="text" name="topic" id="room_topic" list="topic-list" />
            <datalist id="topic-list">
              <select id="room_topic">
                <option value="">Select your topic</option>
                <option value="Python">Python</option>
                <option value="Django">Django</option>
              </select>
            </datalist>

          </div> -->

          <div class="form__action">
            <a class="btn btn--dark" href="{{request.META.HTTP_REFERER}}"
              >Cancel</a
            >
            <button class="btn btn--main" type="submit">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

communities/templates/communities/recent_component.html
<div class="activities">
    <div class="activities__header">
        <h2>Recent Activities</h2>
    </div>
    {% for conversation in goal_conversations %}
    <div class="activities__box">
        <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'profile' conversation.user.username %}" class="roomListRoom__author">
                <div class="avatar avatar--small">
                    <img src="{{conversation.user.userprofile.avatar.url}}" />
                </div>
                <p>
                    @{{conversation.user.username}}
                    <span>{{conversation.created|timesince}} ago</span>
                </p>
            </a>

            {% if request.user == conversation.user %}
            <div class="roomListRoom__actions">
                <a href="{% url 'delete-conversation' conversation.id %}">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>remove</title>
                        <path
                            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                        </path>
                    </svg>
                </a>
            </div>
            {% endif %}

        </div>
        <div class="activities__boxContent">
            <p>replied to post “<a href="{% url 'goal' conversation.goal.id %}">{{conversation.goal}}</a>”</p>
            <div class="activities__boxRoomContent">{{conversation.body}}</div>
        </div>
    </div>
    {% endfor %}

</div>